# Generated by Django 5.2.12 on 2026-07-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_movimientoinventario_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_envase',
            field=models.BooleanField(default=False, help_text='Marcar si es un táper, bolsa o caja para llevar'),
        ),
    ]
