# Generated by Django 5.2.12 on 2026-07-31 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('LOCAL', 'Consumo en Local'), ('LLEVAR', 'Para Llevar')], default='LOCAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.mesa'),
        ),
    ]
