# Generated by Django 5.2.12 on 2026-07-31 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_alter_pedido_mozo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de este ítem cubierto por el pago')),
                ('monto_parcial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_asociados', to='pedidos.detallepedido')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cubiertos', to='pedidos.pago')),
            ],
        ),
    ]
