# Generated by Django 5.2.12 on 2026-07-18 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_cierrecaja_total_otros_sistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrecaja',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_VERIFICACION', 'Pendiente Verificación'), ('CERRADO', 'Cerrado Definitivamente')], default='PENDIENTE_VERIFICACION', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='cierrecaja',
            unique_together={('mozo', 'fecha', 'turno')},
        ),
    ]
