# Generated by Django 5.2.12 on 2026-08-04 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platodeldia',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
